import { Inter } from 'next/font/google';  // Import Google font instead of local fonts
import './globals.css';
import { ClerkProvider } from '@clerk/nextjs'
import Header from '@/components/header';

// Load the Inter font with specified subsets (Latin in this case)
const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
     <ClerkProvider>
    <html lang="en">
      {/* Apply the Inter font class to the body */}
        <body className={inter.className}>
          <Header/>
        {children}
      </body>
      </html>
      </ClerkProvider>
  );
}
